name: test

on:
    push:
        branches:
        - "main"

jobs:
    test_ads:
        runs-on: ubuntu-22.04
        steps:
            - name: Show message
              run: echo "hello word 2024-05-14"
