name: test

on:
    push:
        branches:
        - "main"

env:
    USER_REPOSITORY: Andres

jobs:
    test_ads:
        runs-on: ubuntu-22.04
        steps:
            - name: Show message
              run: echo "hello word 2024-05-14"
            
            - name: Show secret
              run: echo ${{secrets.ENVIROMENT}}

            - name: Show variable in file
              run: echo ${{env.USER_REPOSITORY}}
            
            - name: Show variable GITHUB
              run: echo ${{vars.VERSION}}

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
            
            - name: Test setup 
              run: echo node-version
